-- MySQL Script generated by MySQL Workbench
-- Tue Apr 13 20:24:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` ;
USE `main` ;

-- -----------------------------------------------------
-- Table `main`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` ENUM('small-car', 'family-car', 'van') NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_unique` (`email` ASC, `name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Booking` (
  `customer_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `date_of_hire` DATETIME NOT NULL,
  `date_of_return` DATETIME NOT NULL,
  `retured` TINYINT NOT NULL DEFAULT 0,
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Booking_3_idx` (`employee_id` ASC) ,
  INDEX `fk_Booking_1_idx` (`customer_id` ASC) ,
  CONSTRAINT `fk_Booking_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `main`.`Customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Booking_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `main`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_3`
    FOREIGN KEY (`employee_id`)
    REFERENCES `main`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NULL,
  `amount` FLOAT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_Payment_1_idx` (`booking_id` ASC) ,
  CONSTRAINT `fk_Payment_1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `main`.`Booking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Invoice_1_idx` (`booking_id` ASC) ,
  CONSTRAINT `fk_Invoice_1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `main`.`Booking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Confirmation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Confirmation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(45) NULL,
  `booking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Confirmation_1_idx` (`booking_id` ASC) ,
  CONSTRAINT `fk_Confirmation_1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `main`.`Booking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
